version: '3.0'
services:
  weddingbackend:
    restart: 'no'
    env_file:
      - .env
    environment:
      - AWS_ACCESS_KEY
      - AWS_SECRET_KEY
      - AWS_REGION
      - WEDDING_DB_HOST
      - WEDDING_DB_PORT
      - WEDDING_DB_NAME
      - WEDDING_DB_USER
      - WEDDING_DB_PASSWORD
    ports:
      - '80:5000'
    build:
      context: .
      dockerfile: Dockerfile
