branch-defaults:
  master:
    environment: Terkaberedavidaelbapplication-env
environment-defaults:
  Terkaberedavidaelbapplication-env:
    branch: null
    repository: null
global:
  application_name: TerkaBereDavidaELBApplication
  default_ec2_keyname: null
  default_platform: Docker running on 64bit Amazon Linux 2/3.4.7
  default_region: eu-west-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  sc: git
  workspace_type: Application
