version: 2.1
jobs:
  deploy-backend:
    working_directory: ~/repo
    docker:
      - image: circleci/clojure:lein-2.9.5
    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "project.clj" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: lein deps

      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies-{{ checksum "project.clj" }}

      # run tests!
      - run: lein test

      - run:
          name: Installing deployment dependencies
          command: |
            sudo apt-get -y -qq update
            sudo apt-get install python3-pip python3-dev build-essential
            sudo pip3 install awsebcli

      #- run:
      #    name: Deploy Wedding Docker backend
      #    command: |
      #      eb deploy Terkaberedavidaelbapplication-env
workflows:
  build:
    jobs:
      - deploy-backend
