# Clojure CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-clojure/ for more details
#
version: 2.1

jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/clojure:lein-2.9.5

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/postgres:9.4

    working_directory: ~/repo

    environment:
      LEIN_ROOT: "true"
      # Customize the JVM maximum heap limit
      JVM_OPTS: -Xmx3200m

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "project.clj" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: lein deps

      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies-{{ checksum "project.clj" }}

      # run tests!
      - run: lein test
  deploy-backend:
    working_directory: ~/repo
    docker:
      - image: circleci/clojure:lein-2.9.5
    steps:
      - checkout

      - run:
          name: Installing deployment dependencies
          command: |
            sudo apt-get -y -qq update
            sudo apt-get install python3-pip python3-dev build-essential
            sudo pip3 install awsebcli

      - run:
          name: Deploy Wedding Docker backend
          command: |
            eb deploy Terkaberedavida-env

  deploy-website:

    working_directory: ~/react
    docker:
      - image: circleci/node:8
    steps:
      - checkout

#      - restore_cache:
#          key: npm-cache-v1-{{ checksum "package-lock.json" }}

      - run:
          name: Install Dependencies
          command: |
            npm ci --prefix resources/frontend

#      - save_cache:
#          key: npm-cache-v1-{{ checksum "package-lock.json" }}
#          paths:
#            - /home/circleci/.npm

      - run:
          name: Build React website
          command: |
            npm run --prefix resources/frontend build

      - run:
          name: Deploy Wedding frontend
          command: |
            aws s3 sync resources/frontend/build/ s3://terkaberedavida.cz
            aws cloudfront create-invalidation --distribution-id E73O8TVBW4WB0 --paths "/*" > /dev/null 2>&1

workflows:
  build:
    jobs:
#      - deploy-backend
      - deploy-website
